### ISSUE TITLE
Customer Card Image Stop Showing

### ISSUE THREAD

**Issue by gdreelin** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#1]
When the current update on the HA Mail and Packages 0.1.3 & 1.4 the (/local/mail_and_packages/mail_today.gif) stopped showing up. It shows a broken image link and that gif file is gone now and a randomized (a732c405-579d-41fe-8a7b-d5f4c8feb9b3.gif) file is showing now. How can I check the custom card to fix the image now?

**Comment by gdreelin** [comment]
I see there was an update to displaying the card. I will close this then.

**Comment by tkdrob** [comment]
I'm have this problem now and I just installed this. What did you do to fix it?

**Comment by gdreelin** [comment]
> 
> 
> I'm have this problem now and I just installed this. What did you do to fix it?
> 
> Edit: NVM. I didn't have the gif inside the www folder

the images are in the /img folder. I loaded it from HACS and all worked. When I reinstalled it after the fix it was working fine.
