### ISSUE TITLE
[FEATURE REQUEST] Add support for different Amazon link 

### ISSUE THREAD

**Issue by NdR91** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#14]
Please, can we have the possibility to choose which Amazon Website open with the Link on the Card?

Every person has a different location, so It would be great id everyone can choose to open Amazon.com / uk / it / etc....

![2020-12-18_15-00-39_20](https://user-images.githubusercontent.com/52299148/102623042-2d625c80-4142-11eb-8ea1-b0a64441134c.png)

Thanks =)

**Comment by moralmunky** [comment]
This is included the new pre-release to pair with the next version of the integration.
