### ISSUE TITLE
Allow the card to link to a sensor

### ISSUE THREAD

**Issue by bschatzow** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#17]
**Is your feature request related to a problem? Please describe.**
Allow a link to a contact sensors, motion sensor 
**Describe the solution you'd like**
I have a contact sensor in my mailbox that my automation tells me that my mail has been delivered. I would like to link to this sensor to this card and have the card show the mail has been delivered.
**Describe alternatives you've considered**

**Additional context**

**Comment by moralmunky** [comment]
The card is minimally kept in step with the features of the integration. I don't have plans to add in anything that the integration is not supplying.

**Comment by broyuken** [comment]
You could probably add that info into the message template sensor. Mailbox was last opened at 

{{ as_timestamp(states.binary_sensor.mailbox_door_sensor.last_changed) | timestamp_custom('%A at %H:%M',True) }}
