### ISSUE TITLE
Change "deliveries" to "delivered".

### ISSUE THREAD

**Issue by julianrinaldi** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#21]
**Is your feature request related to a problem? Please describe.**
The word "deliveries" isn't the best word to use. "Deliveries" can be used to describe packages you are expecting to be delivered but haven't been delivered yet, as in "I'm expecting 3 deliveries today". 

**Describe the solution you'd like**
The word "delivered" would be a more appropriate word to use, as its meaning isn't ambiguous.

**Comment by julianrinaldi** [comment]
Also, having the "In Transit" sensor before "Deliveries (or hopefully "Delivered") sensor would make more sense.

**Comment by moralmunky** [comment]
I agree, these changes are implemented in the pre-release.
