### ISSUE TITLE
Request: Delivery Message Centered

### ISSUE THREAD

**Issue by pman07** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#22]
Currently the delivery message is aligned left, could this please be centered?

![image](https://user-images.githubusercontent.com/56171396/110022816-069fd500-7cf2-11eb-9604-4c92e3500d89.png)

I'm trying to fix this, I think `<p>` just needs to be `<p style="text-align:center">`, but I'm too dumb and can't figure out how to get the card to update with the changed .js file. Is there a secret to doing this?

**Comment by pman07** [comment]
I ended up making my own fork to test this, I know I'm being git stoopid, sorry. I ended up getting both the message and icons below to center up a little better by changing `<p>` to `<p style="text-align:center">` and adding `text-align: center;` to `.item`.

Probably a better way of doing this, but it's got me happy for the time being until someone smarter than me can fix in the main project. Thanks!

**Comment by moralmunky** [comment]
I appreciate your feedback. I personally think most centered text is the devil. Getting to know more about the flex box and how to control how the elements align helps solved the inverse pyramid of the package count. We'll see where the new card design leads, it depends on what I how I decide to layout the elements above and below the summary text.
