### ISSUE TITLE
Request: Enlarge mail image when clicked

### ISSUE THREAD

**Issue by julianrinaldi** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#23]
**Is your feature request related to a problem? Please describe.**
Currently when you click on the mail image on the card, it pulls up a history card for when the emails were last checked. This information isn't useful in any way.

![CleanShot 2021-03-06 at 09 00 23](https://user-images.githubusercontent.com/492435/110211614-69fe4400-7e65-11eb-81af-614827f9b52b.png)

**Describe the solution you'd like**
I'd like the mail image to enlarge when clicked on. This is a much more useful use of the card.

**Comment by moralmunky** [comment]
I agree. If you can point me in the right direction I'll add it!

**Comment by nathanfjohnson** [comment]
Here's a way to do it https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card/pull/24

**Comment by moralmunky** [comment]
Thanks, that worked great. Working with the Boiler Plate card provided for HASS and will eventually add it in there.
