### ISSUE TITLE
Excess Whitespace 

### ISSUE THREAD

**Issue by julianrinaldi** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#26]
**Is your feature request related to a problem? Please describe.**
There is a whole lot of extra padding or margin on the card that seems unnecessary, especially above the title and below the "last checked". It takes up much more space than the previous card.

**Describe the solution you'd like**
I'd like the whitespace reduced to the level of the previous card, or even less.

**Additional context**
<img width="452" alt="CleanShot 2021-03-23 at 08 14 42@2x" src="https://user-images.githubusercontent.com/492435/112144972-28cd9a00-8bb0-11eb-9dac-c073856071b6.png">

**Comment by moralmunky** [comment]
Noted, design is preliminary to test functionality in the card rewrite.
