### ISSUE TITLE
Beta v0.7.2.3 Links Not Working

### ISSUE THREAD

**Issue by broyuken** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#30]
**Describe the bug**
The UPS, FedEx and Amazon links don't go to their respective websites.

**To Reproduce**
1. Go to the card
2. Click on UPS, FedEx or Amazon
3. Brings you right back to your HA instance in another tab

**Expected behavior**
Brings you to UPS, FedEx or Amazon website where you can track your orders

**Hass environment (please complete the following information):**
- Type of install
- OS HA OS

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS/Ubuntu
 - Browser [e.g. chrome, safari] App/Firefox
 - Version [e.g. 22] Latest

**Comment by moralmunky** [comment]
Yup, I need to figure out how the recommended development set up works. The files I edit need to go to a clean js file and I think I broke something. The last two edits are only in the source files.
