### ISSUE TITLE
New beta style 

### ISSUE THREAD

**Issue by broyuken** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#31]
Can you put the style back to the way it was in the old card? I like the shipping logos, but the style of the card is way worse now.

**Comment by moralmunky** [comment]
The entire card is in flux, please revert to a non prerelease for a consistent look until the card is finalized. No date is set yet.

**Comment by broyuken** [comment]
I’m not going to revert because I like the info the new card has, just wanted to give some feedback on the look.
