### ISSUE TITLE
v0.7.2.4 blank card

### ISSUE THREAD

**Issue by D34DC3N73R** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#32]
**Describe the bug**
The card appears blank upon creation (no title /content) even after choosing toggles. This is for both the card editor and after it's saved. 

**To Reproduce**
1. Go to 'Edit Dashboard'
2. Click on 'Add Card'
3. Scroll down and click 'Custom: mailandpackages Card'
4. Configure name & desired entities
5. Visual representation of the card remains empty.
6. Save - card remains blank

**Expected behavior**
The entities and title appear on the visual representation of the card in the editor as well as the card itself after being saved.

**Screenshots or Error**
![image](https://user-images.githubusercontent.com/9123670/113088265-1ba94000-919a-11eb-8283-5c1ba00ac745.png)
![image](https://user-images.githubusercontent.com/9123670/113088302-2e237980-919a-11eb-99f7-434f27ff7360.png)

**Hass environment (please complete the following information):**

version | core-2021.3.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.0-70-generic
arch | x86_64

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89.0.4389.90

**Smartphone (please complete the following information):**
N/A

**Additional context**
code editor view of blank card
```
type: 'custom:mailandpackages-card'
name: Mail and Packages
entity_packages_delivered: true
entity_packages_in_transit: true
entity_fedex_packages: true
entity_UPS_packages: true
entity_USPS_packages: true
entity_USPS_exceptions: true
entity_usps_mail: true
show_usps_camera: true
entity_amazon_packages: true
entity_amazon_packages_delivered: true
entity_amazon_hub_packages: true
show_amazon_camera: true
show_warning: true
show_error: true
```

**Comment by drguitarum2005** [comment]
This was resolved for me when I toggled 'warning' and 'error' to off/false
