### ISSUE TITLE
Custom element does not exist

### ISSUE THREAD

**Issue by bschatzow** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#35]
**Describe the bug**
I have several devices and some work correctly. Others give custom element does not exist.  Cleared cache, tried different browsers uninstalled reinstalled. Same error.

**To Reproduce**

**Expected behavior**

**Screenshots or Error**

**Hass environment (please complete the following information):**
- Type of install
- OS

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by moralmunky** [comment]
I am unable to reproduce the issue or receive any console errors in the following OS and Browser combinations:
Safari - Mac: 1.4.1.1
Chrome - Mac: 91.0.4472.77, WIndows: 91.0.4472.101
Firefox - Mac: 87, 89
Edge - Mac: 91.0.864.48, Windows: 91.0.864.41

**Comment by bschatzow** [comment]
Tried the latest beta and same issue. Also have issue in the android app. Cleared cache here as well and no difference.
