### ISSUE TITLE
Custom element doesn't exist

### ISSUE THREAD

**Issue by giffordj** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#37]
**Describe the bug**
Installed as instructions state.

**To Reproduce**
Goto Overview - Select Mail Page
See Error

**Expected behavior**
Expected to see Mail Status Page

**Screenshots or Error**
Screenshot attached
![Error](https://user-images.githubusercontent.com/19445255/139172492-b05a57e7-45dc-4d7f-b958-223b49ff452e.png)

**Hass environment (please complete the following information):**
- HA: Modified Docker Install
-OS:Debian 11

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome - Edge and Firefox
 - 94.0.4606.81  95.0.1020.30 93.0

**Additional context**
All yaml has been validated. Module loads, but isn't seen my HA.

**Comment by moralmunky** [comment]
Which card version did you install? Manually or through HACS?

Did you read through [issue 29](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card/issues/29)?

It has been a cache issue in the past with no rhyme or reason when the front end gets refreshed.

**Comment by giffordj** [comment]
Same issue. In the process of rebuilding. Will update once I get to that point. Also the card is not available in hacs, should it be???
