### ISSUE TITLE
Cant configure for email hotmail.com

### ISSUE THREAD

**Issue by nytram-md** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#38]
![image](https://user-images.githubusercontent.com/55548608/141770897-a9f0d012-ecca-4d33-8b77-e52119ade6b2.png)

Re-installed Mail and Packages and trying to configure

HA 2021.11.3

Ive tried various hosts for hotmail.com and 993 but to no avail with my email account and password. Email and password works as I double checked and signed out to confirm both.

What have I done wrong ?

Thanks

Martyn

**Comment by moralmunky** [comment]
This repository is for the custom card. Please submit this to the [integrations](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages) issues for troubleshooting.

Please see this [section](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Configuration-and-Email-Settings) of the integration wiki for possible help and the linked reference to Microsoft support site on setting up client access through pop or imap.
