### ISSUE TITLE
Amazon image

### ISSUE THREAD

**Issue by Gamerayers** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#41]
Mail and packages now pulls in the image for Amazon deliveries.  Today, I have the USPS mail image enabled, and cannot also have an image for Amazon packages.
Add a area to put the Amazon Package image to the same card.
Should be able to be enabled/disabled like the camera images.

**Comment by moralmunky** [comment]
v0.8.0.0 beta (super old) allows you to turn on everything in a single card, though it's big. I prefer to have two cards with amazon being separate since it isn't counted in the other sensors and the card is more responsive with other cards..
