### ISSUE TITLE
Visual Configuration Editor missing sensor Fields and Dropdowns

### ISSUE THREAD

**Issue by GizmoGoody** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#44]
When I switch to the visual editor, I get a list of all of my available sensors instead of individual fields with dropdowns. This is following a fresh setup of the integration and a HA restart.

![image](https://user-images.githubusercontent.com/46235745/163423128-d67b4235-97da-4873-9a2c-92c78d58cb11.png)

**Comment by stealingzen** [comment]
I have this same issue; hope it's a small issue!

**Comment by moralmunky** [comment]
That version is no longer being worked on. You can try the beta v0.8.0.0

**Comment by GizmoGoody** [comment]
Thanks. I've got it working on v0.8.0.0 and it looks great! How do I submit issues against the beta?
