### ISSUE TITLE
Can not configure card with visual editor (Possibly due to HA bug)

### ISSUE THREAD

**Issue by liquidthex** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#48]
**Describe the bug**
Attempting to use the visual editor to configure the card results in the paper dropdown elements being broken.
This appears to be a known bug on the HA frontend github: https://github.com/home-assistant/frontend/discussions/11294
But there does not appear to be a resolution, so I was hoping this project could be updated to resolve the issue.

**To Reproduce**
1. Input manual YAML for custom card.
2. Switch to visual editor.
3. Visual editor is not correct.

**Expected behavior**
Should be able to configure sensors & options as per screenshot in README.md

**Screenshots or Error**
![image](https://user-images.githubusercontent.com/1348784/198866648-0415a2a4-6f10-4e3e-ad5e-fdd33819e7d0.png)

**Hass environment (please complete the following information):**
- Docker

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 106.0.5249.119

**Additional context**
I love you

**Comment by SharplineX** [comment]
I am having the same issue - any guidance would be appreciated

**Comment by liquidthex** [comment]
I solved the issue by updating my home assistant install, it turns out it
was out of date by quite a while.
