### ISSUE TITLE
Code for Custom Card Shown in README

### ISSUE THREAD

**Issue by badi95** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#7]
The custom card in the README looks great, can you share the code for it in the README?

**Comment by moralmunky** [comment]
You must follow the instruction in the read me. It must be installed.

**Comment by badi95** [comment]
I have it installed and setup the basic card. I really like the card you have a picture of in the readme and was hoping you could share the config for it.

**Comment by moralmunky** [comment]
![Screen Shot 2020-07-29 at 12 26 54 AM](https://user-images.githubusercontent.com/19318945/88756694-4ab27200-d132-11ea-9545-fc2e993dbfd2.png)
You just match the sensors in the visual editor with what you have turned on in the Mail and Packages integration.
